### ISSUE TITLE
clang 11 image on Docker Hub

### ISSUE THREAD

**Issue by gaborcsardi** [silkeh/docker-clang#10]
I am not sure if this is an error, but the clang 11 image is missing from Docker Hub and `latest` is clang 10. 

Thanks for the great project!

**Comment by silkeh** [comment]
Thanks for reporting, it should be availble now.

**Comment by gaborcsardi** [comment]
@silkeh Unfortunately I get this now:

```
root@430faebcf9ab:~# clang --version
clang: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by clang)
clang: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by clang)
```

It seems that clang 11 is not compatible with the glibc and libstdc++ version on buster? Do you want me to open another issue?

**Comment by gaborcsardi** [comment]
FWIW after updating `/etc/apt/sources.list` to `unstable`:
```
# deb http://snapshot.debian.org/archive/debian/20201012T070000Z buster main
deb http://deb.debian.org/debian unstable  main
# deb http://snapshot.debian.org/archive/debian-security/20201012T070000Z buster/updates main
# deb http://security.debian.org/debian-security buster/updates main
# deb http://snapshot.debian.org/archive/debian/20201012T070000Z buster-updates main
# deb http://deb.debian.org/debian buster-updates main
```
and running 
```
apt-get dist-upgrade
```
it works:
```
root@430faebcf9ab:~# clang --version
clang version 11.0.0 (https://github.com/llvm/llvm-project.git 0160ad802e899c2922bc9b29564080c22eb0908c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by silkeh** [comment]
Thanks for noticing! Guess I'll have to add CI here some time...

I have pushed a commit fixing this issue. It should be available shortly, unless Docker Hub decides otherwise. Feel free to let me know if it isn't fixed in an hour or two.

**Comment by gaborcsardi** [comment]
Yes, it indeed works fine now, thanks again!
