### ISSUE TITLE
Clang 12 not available on docker hub

### ISSUE THREAD

**Issue by juliancarrivick** [silkeh/docker-clang#13]
First of all, thank you for maintaining these images, they are really helpful!

I was excited to see https://github.com/silkeh/docker-clang/pull/12 had been merged with some nice updates. It looks like you've published them to docker-hub, however there doesn't seem to be a tag for clang 12.

If you are able to push that, it would be most appreciated!

Thanks again :)

**Comment by silkeh** [comment]
Thanks for the reminder. Build is in progress!

**Comment by silkeh** [comment]
Tag should now be available from Docker hub. Thanks again for letting me know!

**Comment by juliancarrivick** [comment]
Thanks silkeh, just verified that it's available and everything is working. 🍻
