### ISSUE TITLE
let dpkg know that we have a c-compiler?

### ISSUE THREAD

**Issue by emmanuelthome** [silkeh/docker-clang#14]
I like your work!

I came across a slight infelicity this morning. When you want to apt install extra packages, some might depend on a C compiler being around. libtool is one of them.

Under debian, libtool is marked as depending on the virtual package c-compiler, which can be provided by a variety of compilers. Presently, on bullseye this pulls gcc-10 by default.

The sad thing is that your images do have a compiler, of course, and this pull of gcc seems largely unneeded. Would you welcome a modification that creates a phony intermediate package that provides the c-compiler dependency (along with the required symlinks and alternatives set up) ?

**Comment by silkeh** [comment]
Sorry for the late response.

>  Would you welcome a modification that creates a phony intermediate package that provides the c-compiler dependency (along with the required symlinks and alternatives set up) ?

Yes! A dummy package (using `equivs` or equivalent) is definitely welcome!

**Comment by silkeh** [comment]
The images now install the `clang` package from the LLVM Debian repository, which provides `c++-compiler`, `c-compiler`, and `objc-compiler`. This should mean that `dpkg` knows we have a C compiler, but let me know if it doesn't work.

**Comment by emmanuelthome** [comment]
Hi!

That makes perfect sense and solves the problem indeed.

There is still the (comparatively minor) problem that `libtool`, for example, depends on the `cpp` package, and that there is no compiler-agnostic virtual package (like `c-compiler`) that `cpp` would be a provider of. It's not a big deal because we're only talking about pulling a few MB, versus a few dozen MB for a full-blown compiler. Furthermore, I would really say that this is a debian bug, not your bug.

FWIW, my solution was [here](https://gitlab.inria.fr/cado-nfs/cado-nfs/-/tree/master/ci/phony-packages/clang-usrlocal-0.0), and it's freakin ugly. If/when I get back to this, I would definitely check what `equivs` would allow me to do.
