### ISSUE TITLE
Where is Clang 15?

### ISSUE THREAD

**Issue by nlohmann** [silkeh/docker-clang#23]
There is only an image for Clang 14. The `dev` image is already at Clang 16 (16.0.0-++20220929071807+682c7c77f59a-1~exp1~20220929071906.404), but there is no image for Clang 15.

**Comment by jiawen** [comment]
@nlohmann I just posted a preliminary PR #24. It has a number of caveats (listed in the PR description), but it works on my arm64 Mac running Docker desktop.

**Comment by silkeh** [comment]
Unfortunately, there is no linux/amd64 build available for any of the LLVM 15 releases, which is what I currently use. I am working on some new scripts/tooling to build images based on the LLVM Debian repository, but it might take me a while to have that available.

In the meantime, I have pushed `silkeh/clang:15-bullseye` (based on `debian:bullseye-slim`) to try out.

**Comment by andrei-ng** [comment]
@silkeh , latest published `silkeh/clang:15-bullseye` does not seem to have clang-15 inside. 
```
clang --version
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by silkeh** [comment]
Sorry about that. Should be fixed now:
```
# clang --version
Debian clang version 15.0.4-++20221026063345+db68723804fd-1~exp1~20221026063423.87
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by andrei-ng** [comment]
No worries @silkeh . Just wanted to make you aware :wink: . Thanks for fixing it!

**Comment by silkeh** [comment]
I have overhauled the repository and Dockerfile generation, which includes Clang 15 images. See [this commit](https://github.com/silkeh/docker-clang/commit/d633ecf3fbd32b15957c73ecf566d4fffe3bc2d9) for details.

**Comment by nlohmann** [comment]
Thanks!
