### ISSUE TITLE
ARM images ?

### ISSUE THREAD

**Issue by vic1707** [silkeh/docker-clang#25]
Hello,

Just discovered your image and it looks great !
I plan to use it as a base for some of mine and would like to use them on AppleSilicon macs, I saw in `config.yaml` that ARM is listed, but the docker hub images don't support it ?
<img width="550" alt="image" src="https://user-images.githubusercontent.com/28602203/207041985-0ab169b7-0cb4-48a3-b0d4-9678d529504a.png">
Is it a bug, is it normal ?

**Comment by silkeh** [comment]
Thanks for reminding me to take a look at this! The reason for the missing architectures is mainly that a lot of the builds don't work for seemingly supported architectures. 

I have reduced the number of supported images, and updated the CI configuration to build them from now on. Images based on Debian Bullseye should now be available for `linux/amd64`, `linux/arm64/8` and `linux/s390x`.

**Comment by vic1707** [comment]
You're welcome and thank you!
