### ISSUE TITLE
Missing libc++

### ISSUE THREAD

**Issue by jdoubleu** [silkeh/docker-clang#27]
The image is missing `libc++`.

Although it comes with `libstdc++`, which is a requirement of `clang`, I would expect a clang/llvm image to also include `libc++`.

You can simply install it with (as per https://apt.llvm.org/):
```
apt-get install libc++-{version}-dev libc++abi-{version}-dev
```

I think clang will still pick `libstdc++` by default, unless otherwise specified (i.e. `-stdlib=libc++`), so I see no real argument against it. What do you think?

**Comment by jdoubleu** [comment]
thanks!

**Comment by silkeh** [comment]
Thanks for the report! I have included it. Images should be available shortly.
