### ISSUE TITLE
Add support for LLVM 10

### ISSUE THREAD

**Issue by mrexodia** [silkeh/docker-clang#3]
I tried quickly adding support for LLVM 10, but they changed the download URL again so I couldn't get it to work in the existing script... Perhaps it's better to simply hardcode the URLs?

**Comment by silkeh** [comment]
Thanks for the issue! I will take a look at adding this tomorrow.

> Perhaps it's better to simply hardcode the URLs?

Probably, yes. Looks like it's time to perform some cleanup and optimization 🙂

**Comment by silkeh** [comment]
All done. Builds should be coming through in the next few hours (or days, knowing Docker Hub)

> Perhaps it's better to simply hardcode the URLs?

The answer whas clearly more `case` statements :wink:

**Comment by mrexodia** [comment]
Thanks!
