### ISSUE TITLE
fail to link c++17 filesystem with clang

### ISSUE THREAD

**Issue by tuanhtrng** [silkeh/docker-clang#5]
The linker error:

`/usr/bin/ld: CMakeFiles/environment.dir/environment.cpp.o: in function `(anonymous namespace)::environment_t_constructor_Test::TestBody()':
 environment.cpp:(.text+0xc6): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'`

The code compiled on a local clang and a docker gcc.

**Comment by silkeh** [comment]
This looks like an issue with the versions provided by Debian to me. A clean Debian docker image with `build-essential` results in the same error.

**Comment by tuanhtrng** [comment]
Interesting, can you please ship libcxx and see if the errors persist.

**Comment by silkeh** [comment]
[This example](https://en.cppreference.com/w/cpp/filesystem/path/path) compiles using the latest image, so I'm closing this issue. Let me know if the issue persists.
