### ISSUE TITLE
LLVM version of published image in Docker Hub under the tag `10` seems incorrect

### ISSUE THREAD

**Issue by imtsuki** [silkeh/docker-clang#6]
Hi,

Thanks for publishing this useful Docker image, it really helped me a lot!

However, I find it a little annoying that the image published in Docker Hub under the tag `10` (`silkeh/clang:10`) actually has LLVM 9.0 installed in it, which can be found from the [image history](https://hub.docker.com/layers/silkeh/clang/10/images/sha256-63ead5d6e84bf112d48cd2637f6b189b3594399271b4592ce23a3088d412cef7?context=explore). The LLVM version under the tag `latest` is 10.0 btw.

It will be great if you can update this tag!

**Comment by silkeh** [comment]
Thanks for bringing this to my attention! I've fixed the issue in the build configuration on the Docker Hub, and it should be fixed in a few hours.
